version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend/svelte-app"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly" 