services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./:/app
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - FLASK_APP=app.run
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/activmap
      - JWT_SECRET_KEY=votre_cle_secrete_a_changer_en_production
    command: flask run --host=0.0.0.0 --reload

  frontend:
    build:
      context: ./frontend/svelte-app
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8080"
      - "35729:35729"
    volumes:
      - ./frontend/svelte-app:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
    command: npm run dev
      
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=activmap
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  proxy:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/ssl/certs:ro
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  redis_data: 