services:
  backend:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./models.py:/app/models.py
      - ./middleware.py:/app/middleware.py
      - ./init_db.py:/app/init_db.py
      - ./generate_map.py:/app/generate_map.py
    restart: unless-stopped
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - FLASK_APP=app.app
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/activmap
      - JWT_SECRET_KEY=votre_cle_secrete_a_changer_en_production
    command: python app/app.py

  frontend:
    build: ./frontend/svelte-app
    ports:
      - "3000:8080"
    volumes:
      - ./frontend/svelte-app/src:/app/src
      - ./frontend/svelte-app/public:/app/public
    restart: unless-stopped
    depends_on:
      - backend 
      
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=activmap
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: 