FROM node:16-slim

WORKDIR /app

# Copier uniquement les fichiers de dépendances
COPY package*.json ./

# Utiliser un cache npm temporaire pour éviter les problèmes d'accès
ENV npm_config_cache=/tmp/.npm-cache

# Installer les dépendances
RUN npm install --legacy-peer-deps --no-optional

# Exposer le port
EXPOSE 8080

# Le code sera monté depuis l'hôte via les volumes
# Command pour le hot-reload
CMD ["npm", "run", "dev"] 